version: 2

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - build
    - tests

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  errcheck:
    check-blank: false
